### ISSUE TITLE
建议去掉库中titleView，其中attr中的textSize会跟Android自带的design库中textSize有冲突

### ISSUE THREAD

**Issue by wl386123298** [openXu/OXChart#11]
RT

**Comment by openXu** [comment]
TitleLayout中的textSize是沿用android的属性（android:textSize），并不是自定义的，这里不应该有冲突。这个title是demo里面用到的，库里面没有使用，如果不需要是可以删掉的

**Comment by m-gogo** [comment]
我这里也是这个冲突，怎么改
