### ISSUE TITLE
如何导入麻烦给个例子，比如1.8的

### ISSUE THREAD

**Issue by cy9707** [openXu/OXChart#18]
implementation 'com.openxu.viewlib:OXViewLib:<1.8>'  这样吗

**Comment by cy9707** [comment]
我 implementation 'com.openxu.viewlib:OXViewLib:'+ JavaVersion.VERSION_1_8 这样导的时候,build出错Failed to resolve: com.openxu.viewlib:OXViewLib:1.8

**Comment by openXu** [comment]
最新版本上面有说明，类库接入上面       version 1.0.2

 implementation 'com.openxu.viewlib:OXViewLib:1.0.2
