### ISSUE TITLE
 Attribute "titleTextColor" has already been defined

### ISSUE THREAD

**Issue by Ade-rui** [openXu/OXChart#2]
Error:(140) Attribute "titleTextColor" has already been defined
老大 和v7包里面的toolbar自定义属性重复了一个 没办法直接引用了。其他人应该也有这个问题吧 老大有时间改一下啊~~~~~~~~

**Comment by openXu** [comment]
已经解决

**Comment by Ade-rui** [comment]
好的 老大辛苦了  谢谢
