### ISSUE TITLE
请问折线图可以像柱状图一样水平滑动查找更多吗？

### ISSUE THREAD

**Issue by lanceyue** [openXu/OXChart#28]

**Comment by lanceyue** [comment]
> 需要自定义

这个项目中有实现代码？

**Comment by openXu** [comment]
> > 需要自定义
> 
> 这个项目有实现代码吗？



> > 需要自定义
> 
> 这个项目中有实现代码？

没有，你这种需求普通图表框架都没有，只能自己写。有需要的话有偿代写

**Comment by openXu** [comment]
> > 需要自定义
> 
> 这个项目中有实现代码？

没有，你这种需求普通图表框架都没有，只能自己写。有需要的话有偿代写
