### ISSUE TITLE
建议更新代码--按照wiki中的代码，即使赋值数据，饼状图表仍然一直显示灰色

### ISSUE THREAD

**Issue by haiyuKing** [openXu/OXChart#4]
wiki中的代码：pieChart1.setChartData(PieChartBean.class, "Numner", "Name",datalist ,tableList);

我这边正常运行的代码：
pieChart1.setChartData(PieChartBean.class, "**num**", "**name**",datalist ,tableList);
按照PieChartBean类中相应的字段的最新的名称num和name，来进行解决的。理论上讲，应该是这样的。

因为我没有运行demo，所以不清楚demo中是不是正常，如果demo不正常的话，建议作者更新下代码。如果demo正常的话，那就不清楚什么原因了。

**Comment by openXu** [comment]
//参数1：数据类型   参数2：数量字段名称   参数3：名称字段   参数4：数据集合   参数5:lable集合
pieChart1.setChartData(PieChartBean.class, "Numner", "Name",datalist ,tableList);
上面注释已经写得很清楚了
